### PR TITLE
Removes deprecated code

### PR DESCRIPTION
**Pull request by funkyfuture**
these are the overdue removals of deprecated functions and names.

### CODE REVIEW

**Comment by funkyfuture** [comment]
noteworthy: the *xmldiff* is emitting a deprecation warning reg `pkg_resources`. it isn't handled b/c that dependency will likely be removed with the completed serialization.

**Comment by funkyfuture** [comment]
i noticed that some prose related to `Document.config` still mentions removed stuff. could also appear in the *extending* doc.

**Comment by funkyfuture** [comment]
i hope i didn't miss further leftovers. squashed tee fixes with the respective original commits. and i removed the docs related updated, a certain entity (:santa:) requested to deliver it.

**Comment by JKatzwinkel** [comment]
i ran `-mpytest --cov-fefe` and this happened...!?

Screenshot from 2023-12-24 13-24-24

**Comment by funkyfuture** [comment]
isn't fefe at the congress? anyway, how is it different from `just pytest`? what's the purpose? it seems loaders related, is it a network issue?

**Comment by JKatzwinkel** [comment]
yes. gonna replace `http://bdk.london/das_manifest.xml` with alternative source at DTA.

**Comment by JKatzwinkel** [comment]
ok that wasn't it i figure it out later, have to make use of daylight right now!

**Comment by funkyfuture** [comment]
yes, daylight.

> gonna replace `http://bdk.london/das_manifest.xml` with alternative source at DTA.

but that test isn't network-dependent.

**Comment by JKatzwinkel** [comment]
didn't see the response mock anyway lol

**Review by JKatzwinkel — APPROVED** [review]

**Pull request merged**
